config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "snacks#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :snacks do
    resources :bookings, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  patch '/bookings/:id/accept', to: "bookings#accept", as: "accept_booking"
  delete '/bookings/:id', to: "bookings#decline", as: "decline_booking"

  get "/dashboard", to: "pages#dashboard"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :snack
  validates :date, presence: true
  validate :date_cannot_be_in_the_past

  def date_cannot_be_in_the_past
    if date.present? && date < Date.today
      errors.add(:date, "can't be in the past")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :snack
  validates :content, presence: true
  validates :rating, presence: true, numericality: {only_integer: true}, inclusion: { in: 0..5 }
end

app/models/snack.rb
class Snack < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [:name, :description],
    using: {
      tsearch: { prefix: true }
    }

  pg_search_scope :global_search,
  against: [ :name, :description ],
  associated_against: {
    user: [:username]
  },
  using: {
    tsearch: { prefix: true }
  }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  validates :name, :address, presence: true
  validates :price, presence: true

  def rating
    reviews = Review.where(snack_id: id)
    if reviews.any?
      ratings = reviews.map {|review| review.rating }
      (ratings.sum).fdiv(ratings.count).round(2).to_s
    else
      "Non noté"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :snacks
  has_many :bookings

  validates :username, presence: true, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :decline]

  def create
    @booking = Booking.new(booking_params)
    @snack = Snack.find(params[:snack_id])
    @booking.snack = @snack
    @booking.user = current_user
    @booking.booked = false

    if @booking.save
      redirect_to snack_path(@snack), notice: 'La réservation a bien été enregistrée!'
    else
      redirect_to snack_path(@snack), notice: 'La réservation n\'a pas été enregistrée!'
    end
  end

  def accept
    @booking.booked = true
    if @booking.save!
      redirect_to snack_path(@booking.snack), notice: 'La réservation a été acceptée!'
    else
      redirect_to snack_path(@booking.snack), notice: 'La réservation n\'a pas pu être acceptée!'
    end
  end

  def decline
    if @booking.destroy
      redirect_to snack_path(@booking.snack), notice: 'La réservation a été refusée!'
    else
      redirect_to snack_path(@booking.snack), notice: 'La réservation n\'a pas pu être refusée!'
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_snack, only: [:new, :create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.snack = @snack
    @review.user = current_user
    if @review.save
      redirect_to snack_path(@snack)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_snack
    @snack = Snack.find(params[:snack_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
skip_before_action :authenticate_user!, only: [ :index, :show ]
before_action :set_snack, only: [:show, :edit, :update, :destroy]

  def index
    @snacks = Snack.all
    if params[:query].present?
      sql_subquery = <<~SQL
      snacks.name @@ :query
      OR snacks.description @@ :query
      OR users.username @@ :query
      SQL
    @snacks = @snacks.joins(:user).where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @booking = Booking.new
    @markers =
      [{
        lat: @snack.latitude,
        lng: @snack.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { snack: @snack }),
        marker_html: render_to_string(partial: "marker", locals: { snack: @snack })
      }]
  end

  def new
    @snack = Snack.new
  end

  def create
    @snack = Snack.new(snack_params)
    # user_id = current_user.id
    # @snack.user_id = user_id
    @snack.user = current_user
    if @snack.save
      redirect_to snacks_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @snack.update(snack_params)
      redirect_to snack_path(@snack)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @snack.destroy
    redirect_to snacks_path, status: :see_other
  end

  private

  def set_snack
    @snack = Snack.find(params[:id])
  end

  def snack_params
    params.require(:snack).permit(:name, :description, :price, :photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnacksNow</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <div class="content">
          <%= yield %>
      </div>
     <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="dashb-wrapper">

  <h1 class="dashboard-title">Dashboard</h1>
  <p class="dashboard-synopsis">Hey <strong><%= current_user.username %></strong>, envie d'un snack🍫?</p>
  <h5 class="dashb-title-snacks">Tes snacks</h5>
  <div class="dashb-snacks">
      <% current_user.snacks.each do |snack| %>
        <%= link_to snack_path(snack) do %>
          <div class="dashb-card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path snack.photo.key%>)">
          <%= snack.name %>
          </div>
        <% end %>
      <% end %>
  </div>
  <div class="dashb-bookings" data-controller="dashb-switch">

    <h5 class="dashb-title">Tes réservations </h5>
    <div class="switch-div">
      <span> En attente </span>
      <label class="switch">
        <input type="checkbox" data-action="click->dashb-switch#fire">
        <span class="slider round"></span>
      </label>
      <span> Acceptées </span>

    </div>
    <div class="dashb-pending" data-dashb-switch-target="pendingBookings">
        <% current_user.bookings.each do |booking| %>
          <% if booking.booked == false %>
              <%= link_to snack_path(booking.snack) do %>
                <div class="dashb-card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path booking.snack.photo.key%>)">
                  <%= booking.snack.name %>
                </div>
              <% end %>
          <% end %>
        <% end %>
    </div>

    <div class="dashb-accepted d-none" data-dashb-switch-target="acceptedBookings">
        <% current_user.bookings.each do |booking| %>
          <% if booking.booked%>
              <%= link_to snack_path(booking.snack) do %>
                <div class="dashb-card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path booking.snack.photo.key%>)">
                  <%= booking.snack.name %>
                </div>
              <% end %>
          <% end %>
        <% end %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="justify-content-center">

    <% if current_user != @snack.user %>
      <h1 class="h1hh">Ajouter votre avis pour <span class="title-review"><%= @snack.name %></span></h1>
      <div class="descrip">
        <%= simple_form_for [@snack, @review]  do |f|%>
          <%= f.input :content %>
          <%= f.input :rating %>
          <%= f.button :submit, value: "Ajouter", class:"create" %>
        <% end %>
      </div>
    <% else %>
      <p class="hh not-allowed-plz">Vous ne pouvez pas laisser d'avis sur vos propres snacks!</p>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    © 2023 SnacksNow, Inc. • Confidentialité • Conditions générales • Plan du site • Fonctionnement du site • Infos sur l'entreprise
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to snacks_path, class: "navbar-brand" do %>
        <h1 class="navbar-title"> Snack's Now</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <div class="navbar-buttons">

          <li class="nav-item active">
            <%= link_to "Créer un snack", new_snack_path, class: "nav-link" %>
            <%# <%= link_to "Accueil",root_path, class: "nav-link" %>
          </li>
        </div>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "Monamidiego.jpeg", class: "avatar-bordered", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item"%>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <div class="button-light-red">
              <%= link_to "Login", new_user_session_path, class: "nav-link", id: "login" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/snacks/_form_booking.html.erb
<%= simple_form_for [snack, booking] do |f|%>
  <%= f.input :date,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit class: "button-light-red", value: "Confirmer la réservation" %>
<% end %>

app/views/snacks/_info_window.html.erb
<h5><%= snack.name %></h5>
<p><%= snack.address %></p>

app/views/snacks/_marker.html.erb
<%= image_tag "Hotpot.png", height: 60, width: 60, alt: "Logo", class: "twix-icon" %>
<div class="infobulle-name">
  <%= snack.name %>
</div>

app/views/snacks/edit.html.erb
<% if current_user == @snack.user %>
<div class="container d-flex align-items-center justify-content-center ">
    <div class="row w-25">
        <h1 class="text-center fs-3">Modifier <%= @snack.name %></h1>
          <div class="form">
              <%= simple_form_for @snack  do |f|%>
                <%= f.input :name %>
                <%= f.input :description %>
                <%= f.input :address %>
                <%= f.input :price %>
          <%= f.button :submit, "Update Snack", class: "update" %>
          </div>
        <% end %>

    </div>
</div>
<% else %>
  <p>Vous ne pouvez pas modifier ce snack!</p>
<% end %>

app/views/snacks/index.html.erb
<h1 class="index-h1">Snacks of the day</h1>
    <div class="row justify-content-center" class= "searchbar">
        <div class="col-sm-8 my-3">
          <%= form_with url: snacks_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control w-50",
                  placeholder: "𝘔𝘰𝘵𝘴-𝘤𝘭é𝘴"
              %>
              <%= button_tag(type: "submit", class: "button-searchbar", id: "button", onclick: "changeText()" ) do %>
                Miam <i class="fa-solid fa-cookie"></i>
              <% end %>
          <% end %>
        </div>
    </div>
    <script>
  function changeText() {
    const button = document.getElementById("button");
    button.innerHTML = "Miam <i class='fa-solid fa-cookie-bite'></i>";
  }
</script>

  <div class="row justify-content-center">
    <div class="col-sm-8">
      <div id="snacks">
        <% if @snacks.any? %>
          <% @snacks.each do |snack| %>
          <% end %>
        <% else %>
          <em>Nous sommes désolés, aucun snack trouvé.</em>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <% @snacks.each do |snack| %>
      <div class="card-food">
        <%= link_to snack_path(snack) do %>
        <% if snack.photo.attached? %>
          <div class="card-img">
            <%= cl_image_tag snack.photo.key, class: "cl-image" %>
          </div>
        <% else %>
          <div class="card-img">
            <%= image_tag "breakfast.jpg", class: "img-card-index" %>
          </div>
        <% end %>

            <div class="card-content">
              <%= link_to snack_path(snack), class: "link-title-card" do%>
                <h5><%= snack.name %></h5>
                  <div class="card-content-description">
                    <p><%= snack.description %></p>
                  </div>
              <% end %>
          </div>
        </div>
        <% end %>
      <% end %>
  </div>

app/views/snacks/new.html.erb
<div class="container d-flex align-items-center justify-content-center">
    <div class="row">
            <h1 class= "hh">Ajouter un snack</h1>
            <div class="descrip">
            <%= simple_form_for @snack  do |f|%>
              <%= f.input :name %>
              <%= f.input :description %>
              <%= f.input :address %>
              <%= f.input :price %>
              <%= f.input :photo, as: :file %>
              <%= f.button :submit, value: "Ajouter", class:"create" %>
            <% end %>
            </div>
    </div>
</div>

app/views/snacks/show.html.erb
<div class="page-wrapper">

  <div class="show-container">
    <div class="image-div">

  <% if @snack.photo.attached? %>
        <%= cl_image_tag @snack.photo.key, class: "cl-show-image" %>
      <% else %>
        <%= image_tag "breakfast.jpg", class: "cl-show-image" %>
      <% end %>
    </div>

    <div class="show-content">
      <div class="title-div">
        <h1><%= @snack.name %></h1>
        <p> - <%= @snack.rating %> <i class="fa-solid fa-cookie-bite"></i></p>
      </div>

      <div class="description-div">
        <p class="snack-description-card"><%= @snack.description %></p>
      </div>

      <div class="price-div">
        <p class="price-card"><%= @snack.price %>€</p>
        <p><i><span class="created-snack">Ce snack a été créé par <%= @snack.user.username %></span></i></p>
      </div>
    </div>
    <div style="width: 80%; height: auto" class="map-container"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <div class="container-actions">
    <% if user_signed_in? %>
      <%# Si le user est le owner de l'annonce %>
    <% if current_user == @snack.user%>
     <div class="link-snacks">
        <%= link_to "Éditer le snack", edit_snack_path(@snack), class: "edit-snack" %>
        <%= link_to "Supprimer le snack", snack_path(@snack), data: { turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer #{@snack.name}?"}, class: "delete-snack" %>
     </div>



        <div class="booking-container">
          <div class="pending-booking">
          <u><h5 class="title-show">Réservation(s) en attente  <i class="fa-solid fa-clock-rotate-left"></i></h5></u>
            <ul>
              <% @snack.bookings.each do |booking| %>
                <% if booking.booked == false %>
                  <div class="booking-card-show">
                    <li>
                        <p class="booking-demand"><span class="booking-username"><%= booking.user.username %></span> vous a envoyé une demande de réservation</p>
                        <p>pour le <%= booking.date %></p>
                        <p><i class="fa-solid fa-check"></i> <%= link_to "Accepter", accept_booking_path(booking), data: {turbo_method: :patch}, class: "booking-show" %></p>
                        <p><i class="fa-solid fa-xmark"></i> <%= link_to "Refuser", decline_booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Etes-vous sûr de vouloir refuser?"}, class: "booking-show-refuse" %></p>
                    </li>
                  </div>
                <% end %>
            <% end %>
            </ul>
          </div>

          <div class="accepted-booking">
         <u><h5 class="title-show">Réservation(s) acceptées  <i class="fa-solid fa-check"></i></h5></u>
            <ul>
              <% @snack.bookings.each do |booking| %>
                <% if booking.booked%>
                  <li>
                      <%= booking.user.username %> - <%= booking.date %>
                  </li>
                <% end %>
            <% end %>
            </ul>
          </div>
        </div>

    <%# Sinon %>
    <% else %>
      <%# Si on a pas déjà utilisé le user_id et le snack_id, on affiche le lien %>
      <% if Booking.where(user_id:current_user.id, snack_id:@snack.id).empty? %>
        <div data-controller="toggle-booking" class="links-space-container">
          <div class="review-container">

          <div class="link-snacks" data-action="click->toggle-booking#fire">
            <%= link_to "Réservez un snack", class: "snack-reservation"%>

          </div>
          <%# <%= link_to "Réservez un snack", snack_bookings_path(@snack), data: {turbo_method: :post} %>
          <div data-toggle-booking-target="togglableElement" class="d-none">
            <%= render "form_booking", snack: @snack, booking: @booking %>
          </div>
        </div>
          <div class="link-snacks">
              <%= link_to "Laissez un avis", new_snack_review_path(@snack)%>
          </div>
        </div>

      <% else %>
      <% if Booking.where(user_id:current_user.id, snack_id:@snack.id)[0].booked %>
        <p class="resa-validee">Votre réservation a été <span class="green-resa">validée</span> ! Profitez-bien de votre snack aujourd'hui !</p>
      <% else %>
        <p class="resa-pending">Votre demande de réservation est en <span class="cours-de-traitement">cours de traitement</span>, revenez plus tard !</p>
      <% end %>
        <div class="link-snacks">
          <div class="leave-review">
          <%= link_to "Laissez un avis", new_snack_review_path(@snack), class: "review-button"%>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>


   </div>

<% if @snack.reviews.any? %>
    <h5 class="avis-review">Avis</h5>
    <ul>
      <% @snack.reviews.each do |review| %>
        <div class="review-div">
          <% review.rating.times do %>
            <i class="fa-solid fa-cookie-bite"></i>
          <% end %>
          <p><strong><%= review.user.username %></strong>: <%= review.content %></p>
        </div>
      <% end %>
    </ul>
    <% end %>

</div>